import type { Rule } from "./compatibility"

// The rule set §7.3 asks for, as seed data.
//
// Every message is written to the customer, not about the system: it says
// what is wrong and — via `remedy` — what to do instead. §7.10 requires the
// system explain every blocking failure, and "CPU_SOCKET_MISMATCH" explains
// nothing to someone buying their first PC.
//
// Severity follows the BRD's distinction. A part that physically cannot fit
// or connect is blocking. A part that will work but disappoint — a strong
// GPU on a weak CPU, a PSU with no headroom to upgrade — is a warning the
// customer may override after acknowledging it.

export const DEFAULT_COMPATIBILITY_RULES: Rule[] = [
  {
    code: "cpu_socket",
    left_category: "cpu",
    left_attribute: "socket",
    right_category: "motherboard",
    right_attribute: "socket",
    operator: "equals",
    severity: "blocking",
    message: "This processor doesn't fit this motherboard — they use different sockets.",
    remedy: "Pick a motherboard with the same socket as your processor, or choose a different processor.",
  },
  {
    code: "memory_type",
    left_category: "memory",
    left_attribute: "memory_type",
    right_category: "motherboard",
    right_attribute: "supported_memory_types",
    operator: "in",
    severity: "blocking",
    message: "This memory won't fit this motherboard — the board takes a different memory type.",
    remedy: "Choose memory that matches the type your motherboard supports.",
  },
  {
    code: "memory_slots",
    left_category: "memory",
    left_attribute: "sticks",
    right_category: "motherboard",
    right_attribute: "memory_slots",
    operator: "count_lte",
    severity: "blocking",
    message: "You've chosen more memory sticks than this motherboard has slots.",
    remedy: "Use fewer, larger sticks, or pick a board with more slots.",
  },
  {
    code: "memory_capacity",
    left_category: "memory",
    left_attribute: "capacity_gb",
    right_category: "motherboard",
    right_attribute: "max_memory_gb",
    operator: "sum_lte",
    severity: "blocking",
    message: "That's more memory than this motherboard can address.",
    remedy: "Reduce the total memory, or choose a board that supports more.",
  },
  {
    code: "memory_speed",
    left_category: "memory",
    left_attribute: "speed_mhz",
    right_category: "motherboard",
    right_attribute: "max_memory_speed_mhz",
    operator: "lte",
    severity: "warning",
    message: "This memory is faster than the motherboard officially supports, so it will run slower than its rating.",
    remedy: "It will still work. Choose slower memory if you'd rather not pay for speed you can't use.",
  },
  {
    code: "case_form_factor",
    left_category: "motherboard",
    left_attribute: "form_factor",
    right_category: "case",
    right_attribute: "supported_form_factors",
    operator: "in",
    severity: "blocking",
    message: "This motherboard won't fit in this case.",
    remedy: "Pick a larger case, or a smaller motherboard.",
  },
  {
    code: "gpu_clearance",
    left_category: "gpu",
    left_attribute: "length_mm",
    right_category: "case",
    right_attribute: "max_gpu_length_mm",
    operator: "lte",
    severity: "blocking",
    message: "This graphics card is too long for this case.",
    remedy: "Choose a shorter card or a case with more clearance.",
  },
  {
    code: "cooler_clearance",
    left_category: "cpu_cooler",
    left_attribute: "height_mm",
    right_category: "case",
    right_attribute: "max_cooler_height_mm",
    operator: "lte",
    severity: "blocking",
    message: "This CPU cooler is too tall for this case — the side panel won't close.",
    remedy: "Choose a lower-profile cooler, or a case with more clearance.",
  },
  {
    code: "cooler_socket",
    left_category: "cpu_cooler",
    left_attribute: "sockets",
    right_category: "cpu",
    right_attribute: "socket",
    operator: "in",
    severity: "blocking",
    message: "This cooler doesn't have a mounting bracket for your processor's socket.",
    remedy: "Choose a cooler that lists your processor's socket as supported.",
  },
  {
    code: "psu_headroom",
    left_category: "psu",
    left_attribute: "wattage",
    right_category: "gpu",
    right_attribute: "recommended_psu_watts",
    operator: "gte",
    severity: "blocking",
    message: "This power supply doesn't have enough capacity for this graphics card.",
    remedy: "Choose a higher-wattage power supply.",
  },
  {
    code: "psu_margin",
    left_category: "psu",
    left_attribute: "wattage",
    right_category: "gpu",
    right_attribute: "recommended_psu_watts",
    operator: "gte",
    // 1.25x the card's recommendation: enough headroom that the supply is
    // not running at its limit, and room to upgrade the card later.
    factor: 1.25,
    severity: "warning",
    message: "This power supply will run close to its limit with this graphics card.",
    remedy: "It will work, but a larger supply runs quieter and leaves room to upgrade.",
  },
  {
    code: "storage_interface",
    left_category: "storage",
    left_attribute: "interface",
    right_category: "motherboard",
    right_attribute: "supported_storage_interfaces",
    operator: "in",
    severity: "blocking",
    message: "This motherboard doesn't have a connection for this drive.",
    remedy: "Choose a drive that uses an interface your board supports.",
  },
  {
    code: "m2_slots",
    left_category: "storage",
    left_attribute: "uses_m2_slot",
    right_category: "motherboard",
    right_attribute: "m2_slots",
    operator: "sum_lte",
    severity: "blocking",
    message: "You've chosen more M.2 drives than this motherboard has slots.",
    remedy: "Use fewer M.2 drives, or add a SATA drive instead.",
  },
  {
    code: "cpu_gpu_balance",
    left_category: "gpu",
    left_attribute: "tier",
    right_category: "cpu",
    right_attribute: "max_balanced_gpu_tier",
    operator: "lte",
    severity: "warning",
    message: "This graphics card is stronger than this processor can keep up with, so you won't see its full performance.",
    remedy: "A faster processor, or a less expensive card, would give you better value.",
  },
  {
    code: "os_support",
    left_category: "operating_system",
    left_attribute: "requires_tpm",
    right_category: "motherboard",
    right_attribute: "has_tpm",
    operator: "lte",
    severity: "warning",
    message: "This operating system expects a security chip this motherboard doesn't advertise.",
    remedy: "It may still install. Ask us to check before you order if this matters to you.",
  },
]
